package proj;
public class RegisterFile {
	static Register [] registers;
	Register reg0 = new Register();
	Register reg1 = new Register();
	Register reg2 = new Register();
	Register reg3 = new Register();
	Register reg4 = new Register();
	Register reg5 = new Register();
	Register reg6 = new Register();
	Register reg7 = new Register();
	Register reg8 = new Register();
	Register reg9 = new Register();
	Register reg10 = new Register();
	Register reg11 = new Register();
	Register reg12 = new Register();
	Register reg13 = new Register();
	Register reg14 = new Register();
	Register reg15 = new Register();
	Register reg16 = new Register();
	Register reg17 = new Register();
	Register reg18 = new Register();
	Register reg19 = new Register();
	Register reg20 = new Register();
	Register reg21 = new Register();
	Register reg22 = new Register();
	Register reg23 = new Register();
	Register reg24 = new Register();
	Register reg25 = new Register();
	Register reg26 = new Register();
	Register reg27 = new Register();
	Register reg28 = new Register();
	Register reg29 = new Register();
	Register reg30 = new Register();
	Register reg31 = new Register();

	public RegisterFile() {
		reg0.setRegName("$zero");
		reg0.setRegNum(0);
		reg0.setRegValue(0);
		reg1.setRegName("$at");
		reg1.setRegNum(1);
		reg2.setRegName("$v0");
		reg2.setRegNum(2);
		reg3.setRegName("$v1");
		reg3.setRegNum(3);
		reg4.setRegName("$a0");
		reg4.setRegNum(4);
		reg5.setRegName("$a1");
		reg5.setRegNum(5);
		reg6.setRegName("$a2");
		reg6.setRegNum(6);
		reg7.setRegName("$a3");
		reg7.setRegNum(7);
		reg8.setRegName("$t0");
		reg8.setRegNum(8);
		reg9.setRegName("$t1");
		reg9.setRegNum(9);
		reg10.setRegName("$t2");
		reg10.setRegNum(10);
		reg11.setRegName("$t3");
		reg11.setRegNum(11);
		reg12.setRegName("$t4");
		reg12.setRegNum(12);
		reg13.setRegName("$t5");
		reg13.setRegNum(13);
		reg14.setRegName("$t6");
		reg14.setRegNum(14);
		reg15.setRegName("$t7");
		reg15.setRegNum(15);
		reg16.setRegName("$s0");
		reg16.setRegNum(16);
		reg17.setRegName("$s1");
		reg17.setRegNum(17);
		reg18.setRegName("$s2");
		reg18.setRegNum(18);
		reg19.setRegName("$s3");
		reg19.setRegNum(19);
		reg20.setRegName("$s4");
		reg20.setRegNum(20);
		reg21.setRegName("$s5");
		reg21.setRegNum(21);
		reg22.setRegName("$s6");
		reg22.setRegNum(22);
		reg23.setRegName("$s7");
		reg23.setRegNum(23);
		reg24.setRegName("$t8");
		reg24.setRegNum(24);
		reg25.setRegName("$t9");
		reg25.setRegNum(25);
		reg26.setRegName("$k0");
		reg26.setRegNum(26);
		reg27.setRegName("$k1");
		reg27.setRegNum(27);
		reg28.setRegName("$gp");
		reg28.setRegNum(28);
		reg29.setRegName("$sp");
		reg29.setRegNum(29);
		reg30.setRegName("$fp");
		reg30.setRegNum(30);
		reg31.setRegName("$ra");
		reg31.setRegNum(31);
		registers = new Register[32];
		registers[0] = reg0;
		registers[1] = reg1;
		registers[2] = reg2;
		registers[3] = reg3;
		registers[4] = reg4;
		registers[5] = reg5;
		registers[6] = reg6;
		registers[7] = reg7;
		registers[8] = reg8;
		registers[9] = reg9;
		registers[10] = reg10;
		registers[11] = reg11;
		registers[12] = reg12;
		registers[13] = reg13;
		registers[14] = reg14;
		registers[15] = reg15;
		registers[16] = reg16;
		registers[17] = reg17;
		registers[18] = reg18;
		registers[19] = reg19;
		registers[20] = reg20;
		registers[21] = reg21;
		registers[22] = reg22;
		registers[23] = reg23;
		registers[24] = reg24;
		registers[25] = reg25;
		registers[26] = reg26;
		registers[27] = reg27;
		registers[28] = reg28;
		registers[29] = reg29;
		registers[30] = reg30;
		registers[31] = reg31;

	}
}
